/**
 * Typed query-key factory.
 *
 * Centralises query keys so invalidateQueries works reliably across views.
 */
export const qk = {
  dashboardStats: ['dashboard', 'stats'] as const,
  costSummary: (p: string) => ['cost', p] as const,
  usageStats: ['usage-stats'] as const,
  budget: ['budget'] as const,
  budgetGroup: ['budget', 'group'] as const,
  rateLimiting: ['rate-limiting'] as const,
  semanticCache: ['semantic-cache'] as const,
  models: ['models'] as const,
  providers: ['providers'] as const,
  features: ['features'] as const,
  guardrails: ['guardrails'] as const,
  guardrailsStats: ['guardrails', 'stats'] as const,
  piiProtection: ['pii-protection'] as const,
  piiStats: ['pii-stats'] as const,
  piiConfig: ['pii-config'] as const,
  piiPatterns: ['pii-patterns'] as const,
  loopDetection: ['loop-detection'] as const,
  loopSettings: ['loop-settings'] as const,
  circuitBreaker: ['circuit-breaker'] as const,
  fallback: ['fallback'] as const,

  users: ['users'] as const,
  userDetail: (id: number) => ['users', id] as const,
  groups: ['groups'] as const,
  groupDetail: (id: number) => ['groups', id] as const,
  groupMembers: (groupId: number) => ['groups', groupId, 'members'] as const,
  apiKeys: ['api-keys'] as const,
  mcpServers: ['mcp-servers'] as const,
  access: {
    mcp: {
      all: ['access', 'mcp'] as const,
      list: (filters?: Record<string, string>) => ['access', 'mcp', 'list', filters] as const,
      detail: (id: string) => ['access', 'mcp', id] as const,
      defaultPolicy: ['access', 'mcp', 'default-policy'] as const,
    },
  },
  mcpAudit: ['mcp-audit'] as const,
  marketplace: ['mcp-marketplace'] as const,
  prompts: ['prompts'] as const,
  requestsList: (params: Record<string, unknown>) => ['requests', 'list', params] as const,
  requestsDetail: (id: number) => ['requests', 'detail', id] as const,
  requestsOverview: ['requests', 'overview'] as const,
  chat: ['chat'] as const,
  costByKey: (p: string) => ['cost', 'by-key', p] as const,
  topExpensive: ['insights', 'top-expensive'] as const,
  costTrend: (p: string) => ['insights', 'cost-trend', p] as const,
  costByModel: ['insights', 'cost-by-model'] as const,
  savingsOpportunity: ['insights', 'savings-opportunity'] as const,
  jobRuns: (jobId: string, page?: number) => ['jobs', jobId, 'runs', page] as const,
  strategies: ['strategies', 'list'] as const,
  strategyDetail: (name: string) => ['strategies', 'detail', name] as const,
  activeStrategy: ['strategies', 'meta', 'active'] as const,
} as const
