// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: api_keys.sql

package sqlc

import (
	"context"
	"time"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT COUNT(*), COALESCE(SUM(CASE WHEN enabled = 1 THEN 1 ELSE 0 END), 0) FROM api_keys
`

type CountAPIKeysRow struct {
	Count    int64       `json:"count"`
	Coalesce interface{} `json:"coalesce"`
}

func (q *Queries) CountAPIKeys(ctx context.Context) (CountAPIKeysRow, error) {
	row := q.db.QueryRowContext(ctx, countAPIKeys)
	var i CountAPIKeysRow
	err := row.Scan(&i.Count, &i.Coalesce)
	return i, err
}

const createAPIKey = `-- name: CreateAPIKey :exec

INSERT INTO api_keys (
    id, name, hashed_key, salt, key_prefix, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?,
    ?, ?,
    ?, ?, ?,
    ?, ?, ?,
    ?, ?
)
`

type CreateAPIKeyParams struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	HashedKey           string    `json:"hashed_key"`
	Salt                string    `json:"salt"`
	KeyPrefix           *string   `json:"key_prefix"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

// API keys queries.
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, createAPIKey,
		arg.ID,
		arg.Name,
		arg.HashedKey,
		arg.Salt,
		arg.KeyPrefix,
		arg.GroupID,
		arg.UserID,
		arg.Tags,
		arg.MonthlyBudgetUsd,
		arg.MonthlyBudgetTokens,
		arg.RateLimitRpm,
		arg.RateLimitTpm,
		arg.RateLimitRetryAfter,
		arg.AllowedModels,
		arg.AllowedProviders,
		arg.Enabled,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys WHERE id = ?
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteAPIKey, id)
	return err
}

const getAPIKey = `-- name: GetAPIKey :one
SELECT id, name, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at
FROM api_keys
WHERE id = ?
`

type GetAPIKeyRow struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) GetAPIKey(ctx context.Context, id string) (GetAPIKeyRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKey, id)
	var i GetAPIKeyRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.UserID,
		&i.Tags,
		&i.MonthlyBudgetUsd,
		&i.MonthlyBudgetTokens,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.RateLimitRetryAfter,
		&i.AllowedModels,
		&i.AllowedProviders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT id, name, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at
FROM api_keys
WHERE hashed_key = ?
`

type GetAPIKeyByHashRow struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, hashedKey string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyByHash, hashedKey)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.UserID,
		&i.Tags,
		&i.MonthlyBudgetUsd,
		&i.MonthlyBudgetTokens,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.RateLimitRetryAfter,
		&i.AllowedModels,
		&i.AllowedProviders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAPIKeyTeamOrg = `-- name: GetAPIKeyTeamOrg :one
SELECT team_id, org_id FROM api_keys WHERE id = ?
`

type GetAPIKeyTeamOrgRow struct {
	TeamID *string `json:"team_id"`
	OrgID  *string `json:"org_id"`
}

func (q *Queries) GetAPIKeyTeamOrg(ctx context.Context, id string) (GetAPIKeyTeamOrgRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyTeamOrg, id)
	var i GetAPIKeyTeamOrgRow
	err := row.Scan(&i.TeamID, &i.OrgID)
	return i, err
}

const getAPIKeyWithHash = `-- name: GetAPIKeyWithHash :one
SELECT id, name, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at, hashed_key, salt
FROM api_keys
WHERE key_prefix = ? AND salt != 'sha256' AND salt IS NOT NULL AND salt != ''
`

type GetAPIKeyWithHashRow struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	HashedKey           string    `json:"hashed_key"`
	Salt                string    `json:"salt"`
}

func (q *Queries) GetAPIKeyWithHash(ctx context.Context, keyPrefix *string) (GetAPIKeyWithHashRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyWithHash, keyPrefix)
	var i GetAPIKeyWithHashRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.UserID,
		&i.Tags,
		&i.MonthlyBudgetUsd,
		&i.MonthlyBudgetTokens,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.RateLimitRetryAfter,
		&i.AllowedModels,
		&i.AllowedProviders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedKey,
		&i.Salt,
	)
	return i, err
}

const getAPIKeyWithHashNoPrefix = `-- name: GetAPIKeyWithHashNoPrefix :one
SELECT id, name, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at, hashed_key, salt
FROM api_keys
WHERE (key_prefix IS NULL OR key_prefix = '') AND salt != 'sha256' AND salt IS NOT NULL AND salt != ''
`

type GetAPIKeyWithHashNoPrefixRow struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
	HashedKey           string    `json:"hashed_key"`
	Salt                string    `json:"salt"`
}

func (q *Queries) GetAPIKeyWithHashNoPrefix(ctx context.Context) (GetAPIKeyWithHashNoPrefixRow, error) {
	row := q.db.QueryRowContext(ctx, getAPIKeyWithHashNoPrefix)
	var i GetAPIKeyWithHashNoPrefixRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.GroupID,
		&i.UserID,
		&i.Tags,
		&i.MonthlyBudgetUsd,
		&i.MonthlyBudgetTokens,
		&i.RateLimitRpm,
		&i.RateLimitTpm,
		&i.RateLimitRetryAfter,
		&i.AllowedModels,
		&i.AllowedProviders,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.HashedKey,
		&i.Salt,
	)
	return i, err
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, name, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at
FROM api_keys
ORDER BY created_at DESC
`

type ListAPIKeysRow struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysRow{}
	for rows.Next() {
		var i ListAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.UserID,
			&i.Tags,
			&i.MonthlyBudgetUsd,
			&i.MonthlyBudgetTokens,
			&i.RateLimitRpm,
			&i.RateLimitTpm,
			&i.RateLimitRetryAfter,
			&i.AllowedModels,
			&i.AllowedProviders,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeysByGroup = `-- name: ListAPIKeysByGroup :many
SELECT id, name, group_id, user_id, tags,
    monthly_budget_usd, monthly_budget_tokens,
    rate_limit_rpm, rate_limit_tpm, rate_limit_retry_after,
    allowed_models, allowed_providers, enabled,
    created_at, updated_at
FROM api_keys
WHERE group_id = ?
ORDER BY created_at DESC
`

type ListAPIKeysByGroupRow struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

func (q *Queries) ListAPIKeysByGroup(ctx context.Context, groupID *int64) ([]ListAPIKeysByGroupRow, error) {
	rows, err := q.db.QueryContext(ctx, listAPIKeysByGroup, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAPIKeysByGroupRow{}
	for rows.Next() {
		var i ListAPIKeysByGroupRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.GroupID,
			&i.UserID,
			&i.Tags,
			&i.MonthlyBudgetUsd,
			&i.MonthlyBudgetTokens,
			&i.RateLimitRpm,
			&i.RateLimitTpm,
			&i.RateLimitRetryAfter,
			&i.AllowedModels,
			&i.AllowedProviders,
			&i.Enabled,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setKeyRateLimit = `-- name: SetKeyRateLimit :exec
UPDATE api_keys SET rate_limit_rpm = ?, rate_limit_retry_after = ?, updated_at = ?
WHERE id = ?
`

type SetKeyRateLimitParams struct {
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	UpdatedAt           time.Time `json:"updated_at"`
	ID                  string    `json:"id"`
}

func (q *Queries) SetKeyRateLimit(ctx context.Context, arg SetKeyRateLimitParams) error {
	_, err := q.db.ExecContext(ctx, setKeyRateLimit,
		arg.RateLimitRpm,
		arg.RateLimitRetryAfter,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys SET
    name = ?, group_id = ?, user_id = ?, tags = ?,
    monthly_budget_usd = ?, monthly_budget_tokens = ?,
    rate_limit_rpm = ?, rate_limit_tpm = ?,
    allowed_models = ?, allowed_providers = ?,
    enabled = ?, updated_at = ?
WHERE id = ?
`

type UpdateAPIKeyParams struct {
	Name                string    `json:"name"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	UpdatedAt           time.Time `json:"updated_at"`
	ID                  string    `json:"id"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.ExecContext(ctx, updateAPIKey,
		arg.Name,
		arg.GroupID,
		arg.UserID,
		arg.Tags,
		arg.MonthlyBudgetUsd,
		arg.MonthlyBudgetTokens,
		arg.RateLimitRpm,
		arg.RateLimitTpm,
		arg.AllowedModels,
		arg.AllowedProviders,
		arg.Enabled,
		arg.UpdatedAt,
		arg.ID,
	)
	return err
}
