// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit.sql

package sqlc

import (
	"context"
)

const logConfigCreate = `-- name: LogConfigCreate :exec
INSERT INTO config_audit_log (entity_type, entity_id, action, new_values, performed_by)
VALUES (?, ?, 'create', ?, ?)
`

type LogConfigCreateParams struct {
	EntityType  string  `json:"entity_type"`
	EntityID    string  `json:"entity_id"`
	NewValues   *string `json:"new_values"`
	PerformedBy *string `json:"performed_by"`
}

func (q *Queries) LogConfigCreate(ctx context.Context, arg LogConfigCreateParams) error {
	_, err := q.db.ExecContext(ctx, logConfigCreate,
		arg.EntityType,
		arg.EntityID,
		arg.NewValues,
		arg.PerformedBy,
	)
	return err
}

const logConfigDelete = `-- name: LogConfigDelete :exec
INSERT INTO config_audit_log (entity_type, entity_id, action, old_values, performed_by)
VALUES (?, ?, 'delete', ?, ?)
`

type LogConfigDeleteParams struct {
	EntityType  string  `json:"entity_type"`
	EntityID    string  `json:"entity_id"`
	OldValues   *string `json:"old_values"`
	PerformedBy *string `json:"performed_by"`
}

func (q *Queries) LogConfigDelete(ctx context.Context, arg LogConfigDeleteParams) error {
	_, err := q.db.ExecContext(ctx, logConfigDelete,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.PerformedBy,
	)
	return err
}

const logConfigUpdate = `-- name: LogConfigUpdate :exec
INSERT INTO config_audit_log (entity_type, entity_id, action, old_values, new_values, performed_by)
VALUES (?, ?, 'update', ?, ?, ?)
`

type LogConfigUpdateParams struct {
	EntityType  string  `json:"entity_type"`
	EntityID    string  `json:"entity_id"`
	OldValues   *string `json:"old_values"`
	NewValues   *string `json:"new_values"`
	PerformedBy *string `json:"performed_by"`
}

func (q *Queries) LogConfigUpdate(ctx context.Context, arg LogConfigUpdateParams) error {
	_, err := q.db.ExecContext(ctx, logConfigUpdate,
		arg.EntityType,
		arg.EntityID,
		arg.OldValues,
		arg.NewValues,
		arg.PerformedBy,
	)
	return err
}
