// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: config_settings.sql

package sqlc

import (
	"context"
)

const getConfigSetting = `-- name: GetConfigSetting :one

SELECT value FROM config_settings WHERE scope = ? AND scope_id = ? AND field = ?
`

type GetConfigSettingParams struct {
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id"`
	Field   string `json:"field"`
}

// Config settings queries.
func (q *Queries) GetConfigSetting(ctx context.Context, arg GetConfigSettingParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getConfigSetting, arg.Scope, arg.ScopeID, arg.Field)
	var value string
	err := row.Scan(&value)
	return value, err
}
