// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversations.sql

package sqlc

import (
	"context"
	"time"
)

const conversationExists = `-- name: ConversationExists :one
SELECT COUNT(*) FROM conversations WHERE id = ?
`

func (q *Queries) ConversationExists(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, conversationExists, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createConversation = `-- name: CreateConversation :exec
INSERT INTO conversations (id, title) VALUES (?, ?)
`

type CreateConversationParams struct {
	ID    string `json:"id"`
	Title string `json:"title"`
}

func (q *Queries) CreateConversation(ctx context.Context, arg CreateConversationParams) error {
	_, err := q.db.ExecContext(ctx, createConversation, arg.ID, arg.Title)
	return err
}

const deleteConversation = `-- name: DeleteConversation :execrows
DELETE FROM conversations WHERE id = ?
`

func (q *Queries) DeleteConversation(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteConversation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getConversation = `-- name: GetConversation :one
SELECT id, title, created_at, updated_at FROM conversations WHERE id = ?
`

type GetConversationRow struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

func (q *Queries) GetConversation(ctx context.Context, id string) (GetConversationRow, error) {
	row := q.db.QueryRowContext(ctx, getConversation, id)
	var i GetConversationRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getMessageCreatedAt = `-- name: GetMessageCreatedAt :one
SELECT created_at FROM messages WHERE id = ?
`

func (q *Queries) GetMessageCreatedAt(ctx context.Context, id int64) (time.Time, error) {
	row := q.db.QueryRowContext(ctx, getMessageCreatedAt, id)
	var created_at time.Time
	err := row.Scan(&created_at)
	return created_at, err
}

const insertMessage = `-- name: InsertMessage :execlastid
INSERT INTO messages (conversation_id, role, content, model, token_count, cost, reasoning_content, tool_calls, usage_cost, billing_key)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMessageParams struct {
	ConversationID   string   `json:"conversation_id"`
	Role             string   `json:"role"`
	Content          string   `json:"content"`
	Model            *string  `json:"model"`
	TokenCount       *int64   `json:"token_count"`
	Cost             *float64 `json:"cost"`
	ReasoningContent *string  `json:"reasoning_content"`
	ToolCalls        *string  `json:"tool_calls"`
	UsageCost        *float64 `json:"usage_cost"`
	BillingKey       *string  `json:"billing_key"`
}

func (q *Queries) InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, insertMessage,
		arg.ConversationID,
		arg.Role,
		arg.Content,
		arg.Model,
		arg.TokenCount,
		arg.Cost,
		arg.ReasoningContent,
		arg.ToolCalls,
		arg.UsageCost,
		arg.BillingKey,
	)
	if err != nil {
		return 0, err
	}
	return result.LastInsertId()
}

const listConversations = `-- name: ListConversations :many

SELECT
    c.id, c.title, c.created_at, c.updated_at,
    CAST(COALESCE((SELECT content FROM messages WHERE conversation_id = c.id ORDER BY created_at DESC LIMIT 1), '') AS TEXT) AS last_message,
    CAST(COALESCE((SELECT COUNT(*) FROM messages WHERE conversation_id = c.id), 0) AS INTEGER) AS message_count
FROM conversations c
ORDER BY c.updated_at DESC
`

type ListConversationsRow struct {
	ID           string    `json:"id"`
	Title        string    `json:"title"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
	LastMessage  string    `json:"last_message"`
	MessageCount int64     `json:"message_count"`
}

// Chat conversations and messages (dashboard chat UI).
func (q *Queries) ListConversations(ctx context.Context) ([]ListConversationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listConversations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListConversationsRow{}
	for rows.Next() {
		var i ListConversationsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.LastMessage,
			&i.MessageCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesByConversation = `-- name: ListMessagesByConversation :many
SELECT id, conversation_id, role, content, model, token_count, cost, reasoning_content, tool_calls, usage_cost, billing_key, created_at
FROM messages
WHERE conversation_id = ?
ORDER BY created_at ASC
`

func (q *Queries) ListMessagesByConversation(ctx context.Context, conversationID string) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesByConversation, conversationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.TokenCount,
			&i.Cost,
			&i.ReasoningContent,
			&i.ToolCalls,
			&i.UsageCost,
			&i.BillingKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMessagesPaginated = `-- name: ListMessagesPaginated :many
SELECT id, conversation_id, role, content, model, token_count, cost, reasoning_content, tool_calls, usage_cost, billing_key, created_at
FROM messages
WHERE conversation_id = ?1
  AND (CAST(?2 AS INTEGER) IS NULL OR id < CAST(?2 AS INTEGER))
ORDER BY created_at DESC LIMIT ?3
`

type ListMessagesPaginatedParams struct {
	ConversationID string `json:"conversation_id"`
	BeforeID       *int64 `json:"before_id"`
	Limit          int64  `json:"limit"`
}

func (q *Queries) ListMessagesPaginated(ctx context.Context, arg ListMessagesPaginatedParams) ([]Message, error) {
	rows, err := q.db.QueryContext(ctx, listMessagesPaginated, arg.ConversationID, arg.BeforeID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Message{}
	for rows.Next() {
		var i Message
		if err := rows.Scan(
			&i.ID,
			&i.ConversationID,
			&i.Role,
			&i.Content,
			&i.Model,
			&i.TokenCount,
			&i.Cost,
			&i.ReasoningContent,
			&i.ToolCalls,
			&i.UsageCost,
			&i.BillingKey,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setConversationTitle = `-- name: SetConversationTitle :exec
UPDATE conversations SET title = ? WHERE id = ?
`

type SetConversationTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) error {
	_, err := q.db.ExecContext(ctx, setConversationTitle, arg.Title, arg.ID)
	return err
}

const touchConversation = `-- name: TouchConversation :exec
UPDATE conversations SET updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

func (q *Queries) TouchConversation(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, touchConversation, id)
	return err
}

const updateConversationTitle = `-- name: UpdateConversationTitle :execrows
UPDATE conversations SET title = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type UpdateConversationTitleParams struct {
	Title string `json:"title"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateConversationTitle, arg.Title, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
