// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: groups.sql

package sqlc

import (
	"context"
	"database/sql"
)

const addUserToGroup = `-- name: AddUserToGroup :exec
INSERT INTO user_group_memberships (user_id, group_id, role) VALUES (?, ?, ?)
`

type AddUserToGroupParams struct {
	UserID  int64  `json:"user_id"`
	GroupID int64  `json:"group_id"`
	Role    string `json:"role"`
}

func (q *Queries) AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error {
	_, err := q.db.ExecContext(ctx, addUserToGroup, arg.UserID, arg.GroupID, arg.Role)
	return err
}

const createGroup = `-- name: CreateGroup :execresult

INSERT INTO groups (name, description, metadata, budget)
VALUES (?, ?, '{}', ?)
`

type CreateGroupParams struct {
	Name        string   `json:"name"`
	Description *string  `json:"description"`
	Budget      *float64 `json:"budget"`
}

// Groups and group membership queries.
func (q *Queries) CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createGroup, arg.Name, arg.Description, arg.Budget)
}

const deleteGroup = `-- name: DeleteGroup :execrows
DELETE FROM groups WHERE id = ?
`

func (q *Queries) DeleteGroup(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGroup, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getGroup = `-- name: GetGroup :one
SELECT id, name, description, metadata, budget, daily_limit, created_at, updated_at
FROM groups WHERE id = ?
`

func (q *Queries) GetGroup(ctx context.Context, id int64) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroup, id)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.Budget,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupBudget = `-- name: GetGroupBudget :one
SELECT budget, daily_limit FROM groups WHERE id = ?
`

type GetGroupBudgetRow struct {
	Budget     *float64 `json:"budget"`
	DailyLimit *float64 `json:"daily_limit"`
}

func (q *Queries) GetGroupBudget(ctx context.Context, id int64) (GetGroupBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, getGroupBudget, id)
	var i GetGroupBudgetRow
	err := row.Scan(&i.Budget, &i.DailyLimit)
	return i, err
}

const getGroupByName = `-- name: GetGroupByName :one
SELECT id, name, description, metadata, budget, daily_limit, created_at, updated_at
FROM groups WHERE name = ?
`

func (q *Queries) GetGroupByName(ctx context.Context, name string) (Group, error) {
	row := q.db.QueryRowContext(ctx, getGroupByName, name)
	var i Group
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Metadata,
		&i.Budget,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getGroupUsers = `-- name: GetGroupUsers :many
SELECT u.id, u.name, u.email, u.status, u.password_hash, u.metadata, u.budget, u.daily_limit, u.created_at, u.updated_at
FROM users u
JOIN user_group_memberships m ON u.id = m.user_id
WHERE m.group_id = ?
ORDER BY u.id
`

func (q *Queries) GetGroupUsers(ctx context.Context, groupID int64) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, getGroupUsers, groupID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.PasswordHash,
			&i.Metadata,
			&i.Budget,
			&i.DailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserGroups = `-- name: GetUserGroups :many
SELECT g.id, g.name, g.description, g.metadata, g.budget, g.daily_limit, g.created_at, g.updated_at
FROM groups g
JOIN user_group_memberships m ON g.id = m.group_id
WHERE m.user_id = ?
ORDER BY g.id
`

func (q *Queries) GetUserGroups(ctx context.Context, userID int64) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, getUserGroups, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Metadata,
			&i.Budget,
			&i.DailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGroups = `-- name: ListGroups :many
SELECT id, name, description, metadata, budget, daily_limit, created_at, updated_at
FROM groups ORDER BY id
`

func (q *Queries) ListGroups(ctx context.Context) ([]Group, error) {
	rows, err := q.db.QueryContext(ctx, listGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Group{}
	for rows.Next() {
		var i Group
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Metadata,
			&i.Budget,
			&i.DailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromGroup = `-- name: RemoveUserFromGroup :execrows
DELETE FROM user_group_memberships WHERE user_id = ? AND group_id = ?
`

type RemoveUserFromGroupParams struct {
	UserID  int64 `json:"user_id"`
	GroupID int64 `json:"group_id"`
}

func (q *Queries) RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, removeUserFromGroup, arg.UserID, arg.GroupID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
