// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: guardrails.sql

package sqlc

import (
	"context"
)

const createGuardrailRule = `-- name: CreateGuardrailRule :exec
INSERT INTO guardrail_rules (id, name, description, patterns, mode, severity, target_type, target_id, type)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateGuardrailRuleParams struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Patterns    string  `json:"patterns"`
	Mode        string  `json:"mode"`
	Severity    string  `json:"severity"`
	TargetType  *string `json:"target_type"`
	TargetID    *int64  `json:"target_id"`
	Type        string  `json:"type"`
}

func (q *Queries) CreateGuardrailRule(ctx context.Context, arg CreateGuardrailRuleParams) error {
	_, err := q.db.ExecContext(ctx, createGuardrailRule,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Patterns,
		arg.Mode,
		arg.Severity,
		arg.TargetType,
		arg.TargetID,
		arg.Type,
	)
	return err
}

const deleteGuardrailRule = `-- name: DeleteGuardrailRule :execrows
DELETE FROM guardrail_rules WHERE id = ?
`

func (q *Queries) DeleteGuardrailRule(ctx context.Context, id string) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteGuardrailRule, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getEnabledGuardrailRules = `-- name: GetEnabledGuardrailRules :many
SELECT id, COALESCE(type, 'custom') AS type, patterns, mode, severity,
    COALESCE(target_type, 'global') AS target_type, target_id
FROM guardrail_rules
WHERE enabled = 1
ORDER BY severity DESC, name
`

type GetEnabledGuardrailRulesRow struct {
	ID         string `json:"id"`
	Type       string `json:"type"`
	Patterns   string `json:"patterns"`
	Mode       string `json:"mode"`
	Severity   string `json:"severity"`
	TargetType string `json:"target_type"`
	TargetID   *int64 `json:"target_id"`
}

func (q *Queries) GetEnabledGuardrailRules(ctx context.Context) ([]GetEnabledGuardrailRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEnabledGuardrailRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetEnabledGuardrailRulesRow{}
	for rows.Next() {
		var i GetEnabledGuardrailRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Patterns,
			&i.Mode,
			&i.Severity,
			&i.TargetType,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertGuardrailEvent = `-- name: InsertGuardrailEvent :exec
INSERT INTO guardrail_events (key_id, guardrail_type, action_taken, model, provider, details)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertGuardrailEventParams struct {
	KeyID         *string `json:"key_id"`
	GuardrailType string  `json:"guardrail_type"`
	ActionTaken   string  `json:"action_taken"`
	Model         *string `json:"model"`
	Provider      *string `json:"provider"`
	Details       *string `json:"details"`
}

func (q *Queries) InsertGuardrailEvent(ctx context.Context, arg InsertGuardrailEventParams) error {
	_, err := q.db.ExecContext(ctx, insertGuardrailEvent,
		arg.KeyID,
		arg.GuardrailType,
		arg.ActionTaken,
		arg.Model,
		arg.Provider,
		arg.Details,
	)
	return err
}

const listGuardrailRules = `-- name: ListGuardrailRules :many

SELECT id, name, COALESCE(type, 'custom') AS type, mode, severity, enabled,
    COALESCE(target_type, 'global') AS target_type, target_id
FROM guardrail_rules
ORDER BY name
`

type ListGuardrailRulesRow struct {
	ID         string `json:"id"`
	Name       string `json:"name"`
	Type       string `json:"type"`
	Mode       string `json:"mode"`
	Severity   string `json:"severity"`
	Enabled    int64  `json:"enabled"`
	TargetType string `json:"target_type"`
	TargetID   *int64 `json:"target_id"`
}

// Guardrail rules (CRUD) and guardrail events (write path).
func (q *Queries) ListGuardrailRules(ctx context.Context) ([]ListGuardrailRulesRow, error) {
	rows, err := q.db.QueryContext(ctx, listGuardrailRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListGuardrailRulesRow{}
	for rows.Next() {
		var i ListGuardrailRulesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Type,
			&i.Mode,
			&i.Severity,
			&i.Enabled,
			&i.TargetType,
			&i.TargetID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const toggleGuardrailRule = `-- name: ToggleGuardrailRule :execrows
UPDATE guardrail_rules SET enabled = ?, updated_at = CURRENT_TIMESTAMP WHERE id = ?
`

type ToggleGuardrailRuleParams struct {
	Enabled int64  `json:"enabled"`
	ID      string `json:"id"`
}

func (q *Queries) ToggleGuardrailRule(ctx context.Context, arg ToggleGuardrailRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, toggleGuardrailRule, arg.Enabled, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const updateGuardrailRule = `-- name: UpdateGuardrailRule :execrows
UPDATE guardrail_rules
SET name = COALESCE(NULLIF(CAST(?1 AS TEXT), ''), name),
    type = COALESCE(NULLIF(CAST(?2 AS TEXT), ''), type),
    description = COALESCE(NULLIF(CAST(?3 AS TEXT), ''), description),
    patterns = CASE WHEN CAST(?4 AS TEXT) = '[]' THEN patterns ELSE CAST(?4 AS TEXT) END,
    mode = COALESCE(NULLIF(CAST(?5 AS TEXT), ''), mode),
    severity = COALESCE(NULLIF(CAST(?6 AS TEXT), ''), severity),
    enabled = COALESCE(?7, enabled),
    target_type = COALESCE(?8, target_type),
    target_id = COALESCE(?9, target_id),
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?10
`

type UpdateGuardrailRuleParams struct {
	Name        string  `json:"name"`
	Type        string  `json:"type"`
	Description string  `json:"description"`
	Patterns    string  `json:"patterns"`
	Mode        string  `json:"mode"`
	Severity    string  `json:"severity"`
	Enabled     *int64  `json:"enabled"`
	TargetType  *string `json:"target_type"`
	TargetID    *int64  `json:"target_id"`
	ID          string  `json:"id"`
}

func (q *Queries) UpdateGuardrailRule(ctx context.Context, arg UpdateGuardrailRuleParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, updateGuardrailRule,
		arg.Name,
		arg.Type,
		arg.Description,
		arg.Patterns,
		arg.Mode,
		arg.Severity,
		arg.Enabled,
		arg.TargetType,
		arg.TargetID,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
