// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: key_usage.sql

package sqlc

import (
	"context"
)

const getCurrentMonthUsage = `-- name: GetCurrentMonthUsage :one
SELECT COALESCE(SUM(cost_usd), 0) FROM key_usage
WHERE key_id = ? AND date >= ? AND date <= ?
`

type GetCurrentMonthUsageParams struct {
	KeyID  string `json:"key_id"`
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
}

func (q *Queries) GetCurrentMonthUsage(ctx context.Context, arg GetCurrentMonthUsageParams) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getCurrentMonthUsage, arg.KeyID, arg.Date, arg.Date_2)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getKeyUsage = `-- name: GetKeyUsage :many
SELECT key_id, date, tokens_in, tokens_out, cost_usd, request_count, model, provider
FROM key_usage
WHERE key_id = ? AND date >= ? AND date <= ?
ORDER BY date DESC, model ASC
`

type GetKeyUsageParams struct {
	KeyID  string `json:"key_id"`
	Date   string `json:"date"`
	Date_2 string `json:"date_2"`
}

type GetKeyUsageRow struct {
	KeyID        string   `json:"key_id"`
	Date         string   `json:"date"`
	TokensIn     *int64   `json:"tokens_in"`
	TokensOut    *int64   `json:"tokens_out"`
	CostUsd      *float64 `json:"cost_usd"`
	RequestCount *int64   `json:"request_count"`
	Model        *string  `json:"model"`
	Provider     *string  `json:"provider"`
}

func (q *Queries) GetKeyUsage(ctx context.Context, arg GetKeyUsageParams) ([]GetKeyUsageRow, error) {
	rows, err := q.db.QueryContext(ctx, getKeyUsage, arg.KeyID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetKeyUsageRow{}
	for rows.Next() {
		var i GetKeyUsageRow
		if err := rows.Scan(
			&i.KeyID,
			&i.Date,
			&i.TokensIn,
			&i.TokensOut,
			&i.CostUsd,
			&i.RequestCount,
			&i.Model,
			&i.Provider,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsageSummary = `-- name: GetUsageSummary :one
SELECT COALESCE(SUM(request_count),0), COALESCE(SUM(cost_usd),0), COALESCE(SUM(tokens_in),0), COALESCE(SUM(tokens_out),0) FROM key_usage
`

type GetUsageSummaryRow struct {
	Coalesce   interface{} `json:"coalesce"`
	Coalesce_2 interface{} `json:"coalesce_2"`
	Coalesce_3 interface{} `json:"coalesce_3"`
	Coalesce_4 interface{} `json:"coalesce_4"`
}

func (q *Queries) GetUsageSummary(ctx context.Context) (GetUsageSummaryRow, error) {
	row := q.db.QueryRowContext(ctx, getUsageSummary)
	var i GetUsageSummaryRow
	err := row.Scan(
		&i.Coalesce,
		&i.Coalesce_2,
		&i.Coalesce_3,
		&i.Coalesce_4,
	)
	return i, err
}

const recordKeyUsage = `-- name: RecordKeyUsage :exec

INSERT INTO key_usage (key_id, date, tokens_in, tokens_out, cost_usd, request_count, model, provider)
VALUES (?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(key_id, date, model, provider) DO UPDATE SET
    tokens_in = tokens_in + excluded.tokens_in,
    tokens_out = tokens_out + excluded.tokens_out,
    cost_usd = cost_usd + excluded.cost_usd,
    request_count = request_count + excluded.request_count
`

type RecordKeyUsageParams struct {
	KeyID        string   `json:"key_id"`
	Date         string   `json:"date"`
	TokensIn     *int64   `json:"tokens_in"`
	TokensOut    *int64   `json:"tokens_out"`
	CostUsd      *float64 `json:"cost_usd"`
	RequestCount *int64   `json:"request_count"`
	Model        *string  `json:"model"`
	Provider     *string  `json:"provider"`
}

// Key usage aggregation queries.
func (q *Queries) RecordKeyUsage(ctx context.Context, arg RecordKeyUsageParams) error {
	_, err := q.db.ExecContext(ctx, recordKeyUsage,
		arg.KeyID,
		arg.Date,
		arg.TokensIn,
		arg.TokensOut,
		arg.CostUsd,
		arg.RequestCount,
		arg.Model,
		arg.Provider,
	)
	return err
}
