// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp.sql

package sqlc

import (
	"context"
	"encoding/json"
)

const deleteMCPToolsByServer = `-- name: DeleteMCPToolsByServer :exec
DELETE FROM mcp_tools WHERE server_id = ?
`

func (q *Queries) DeleteMCPToolsByServer(ctx context.Context, serverID string) error {
	_, err := q.db.ExecContext(ctx, deleteMCPToolsByServer, serverID)
	return err
}

const listMCPServers = `-- name: ListMCPServers :many

SELECT id, name, description, transport, url, command, args, env,
       handler, enabled, timeout_ms, max_retries, auth_type, auth_key_env
FROM mcp_servers
`

type ListMCPServersRow struct {
	ID          string  `json:"id"`
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Transport   string  `json:"transport"`
	Url         *string `json:"url"`
	Command     *string `json:"command"`
	Args        *string `json:"args"`
	Env         *string `json:"env"`
	Handler     *string `json:"handler"`
	Enabled     int64   `json:"enabled"`
	TimeoutMs   *int64  `json:"timeout_ms"`
	MaxRetries  int64   `json:"max_retries"`
	AuthType    *string `json:"auth_type"`
	AuthKeyEnv  *string `json:"auth_key_env"`
}

// MCP server registry: servers config and their discovered tools.
func (q *Queries) ListMCPServers(ctx context.Context) ([]ListMCPServersRow, error) {
	rows, err := q.db.QueryContext(ctx, listMCPServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPServersRow{}
	for rows.Next() {
		var i ListMCPServersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Transport,
			&i.Url,
			&i.Command,
			&i.Args,
			&i.Env,
			&i.Handler,
			&i.Enabled,
			&i.TimeoutMs,
			&i.MaxRetries,
			&i.AuthType,
			&i.AuthKeyEnv,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMCPTools = `-- name: ListMCPTools :many
SELECT name, description, schema
FROM mcp_tools
WHERE server_id = ?
ORDER BY name
`

type ListMCPToolsRow struct {
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Schema      json.RawMessage `json:"schema"`
}

func (q *Queries) ListMCPTools(ctx context.Context, serverID string) ([]ListMCPToolsRow, error) {
	rows, err := q.db.QueryContext(ctx, listMCPTools, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMCPToolsRow{}
	for rows.Next() {
		var i ListMCPToolsRow
		if err := rows.Scan(&i.Name, &i.Description, &i.Schema); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertMCPTool = `-- name: UpsertMCPTool :exec
INSERT OR REPLACE INTO mcp_tools (id, server_id, name, description, schema)
VALUES (?, ?, ?, ?, ?)
`

type UpsertMCPToolParams struct {
	ID          string          `json:"id"`
	ServerID    string          `json:"server_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Schema      json.RawMessage `json:"schema"`
}

func (q *Queries) UpsertMCPTool(ctx context.Context, arg UpsertMCPToolParams) error {
	_, err := q.db.ExecContext(ctx, upsertMCPTool,
		arg.ID,
		arg.ServerID,
		arg.Name,
		arg.Description,
		arg.Schema,
	)
	return err
}
