// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mcp_tasks.sql

package sqlc

import (
	"context"
	"encoding/json"
	"time"
)

const createMCPTask = `-- name: CreateMCPTask :exec

INSERT INTO mcp_tasks (id, key_id, server_id, tool_name, arguments, status, result, input_required_payload, expires_at)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateMCPTaskParams struct {
	ID                   string          `json:"id"`
	KeyID                *string         `json:"key_id"`
	ServerID             *string         `json:"server_id"`
	ToolName             string          `json:"tool_name"`
	Arguments            json.RawMessage `json:"arguments"`
	Status               string          `json:"status"`
	Result               json.RawMessage `json:"result"`
	InputRequiredPayload json.RawMessage `json:"input_required_payload"`
	ExpiresAt            time.Time       `json:"expires_at"`
}

// Backing store for the MCP Tasks extension (2026-07-28 only).
func (q *Queries) CreateMCPTask(ctx context.Context, arg CreateMCPTaskParams) error {
	_, err := q.db.ExecContext(ctx, createMCPTask,
		arg.ID,
		arg.KeyID,
		arg.ServerID,
		arg.ToolName,
		arg.Arguments,
		arg.Status,
		arg.Result,
		arg.InputRequiredPayload,
		arg.ExpiresAt,
	)
	return err
}

const deleteExpiredMCPTasks = `-- name: DeleteExpiredMCPTasks :exec
DELETE FROM mcp_tasks WHERE expires_at < datetime('now')
`

func (q *Queries) DeleteExpiredMCPTasks(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteExpiredMCPTasks)
	return err
}

const getMCPTask = `-- name: GetMCPTask :one
SELECT id, key_id, server_id, tool_name, arguments, status, result,
       input_required_payload, error_message, created_at, updated_at, expires_at
FROM mcp_tasks WHERE id = ?
`

func (q *Queries) GetMCPTask(ctx context.Context, id string) (McpTask, error) {
	row := q.db.QueryRowContext(ctx, getMCPTask, id)
	var i McpTask
	err := row.Scan(
		&i.ID,
		&i.KeyID,
		&i.ServerID,
		&i.ToolName,
		&i.Arguments,
		&i.Status,
		&i.Result,
		&i.InputRequiredPayload,
		&i.ErrorMessage,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const updateMCPTaskInputRequired = `-- name: UpdateMCPTaskInputRequired :exec
UPDATE mcp_tasks
SET status = 'input_required', input_required_payload = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateMCPTaskInputRequiredParams struct {
	InputRequiredPayload json.RawMessage `json:"input_required_payload"`
	ID                   string          `json:"id"`
}

func (q *Queries) UpdateMCPTaskInputRequired(ctx context.Context, arg UpdateMCPTaskInputRequiredParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPTaskInputRequired, arg.InputRequiredPayload, arg.ID)
	return err
}

const updateMCPTaskStatus = `-- name: UpdateMCPTaskStatus :exec
UPDATE mcp_tasks
SET status = ?, result = ?, error_message = ?, updated_at = datetime('now')
WHERE id = ?
`

type UpdateMCPTaskStatusParams struct {
	Status       string          `json:"status"`
	Result       json.RawMessage `json:"result"`
	ErrorMessage *string         `json:"error_message"`
	ID           string          `json:"id"`
}

func (q *Queries) UpdateMCPTaskStatus(ctx context.Context, arg UpdateMCPTaskStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateMCPTaskStatus,
		arg.Status,
		arg.Result,
		arg.ErrorMessage,
		arg.ID,
	)
	return err
}
