// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"encoding/json"
	"time"
)

type ApiKey struct {
	ID                  string    `json:"id"`
	Name                string    `json:"name"`
	HashedKey           string    `json:"hashed_key"`
	Salt                string    `json:"salt"`
	KeyPrefix           *string   `json:"key_prefix"`
	GroupID             *int64    `json:"group_id"`
	UserID              *int64    `json:"user_id"`
	Tags                *string   `json:"tags"`
	MonthlyBudgetUsd    *float64  `json:"monthly_budget_usd"`
	MonthlyBudgetTokens *int64    `json:"monthly_budget_tokens"`
	RateLimitRpm        *int64    `json:"rate_limit_rpm"`
	RateLimitTpm        *int64    `json:"rate_limit_tpm"`
	RateLimitRetryAfter *int64    `json:"rate_limit_retry_after"`
	AllowedModels       *string   `json:"allowed_models"`
	AllowedProviders    *string   `json:"allowed_providers"`
	Enabled             int64     `json:"enabled"`
	TeamID              *string   `json:"team_id"`
	OrgID               *string   `json:"org_id"`
	CreatedAt           time.Time `json:"created_at"`
	UpdatedAt           time.Time `json:"updated_at"`
}

type AuditBody struct {
	ID            int64   `json:"id"`
	AuditLogID    int64   `json:"audit_log_id"`
	RequestBody   *string `json:"request_body"`
	ResponseBody  *string `json:"response_body"`
	PromptPreview *string `json:"prompt_preview"`
	Compressed    int64   `json:"compressed"`
}

type AuditLog struct {
	ID                 int64      `json:"id"`
	Timestamp          *time.Time `json:"timestamp"`
	KeyID              *string    `json:"key_id"`
	Model              *string    `json:"model"`
	Provider           *string    `json:"provider"`
	PromptTokens       *int64     `json:"prompt_tokens"`
	CompletionTokens   *int64     `json:"completion_tokens"`
	TotalCost          *float64   `json:"total_cost"`
	LatencyMs          *int64     `json:"latency_ms"`
	StatusCode         *int64     `json:"status_code"`
	CacheHit           *bool      `json:"cache_hit"`
	PromptPreview      *string    `json:"prompt_preview"`
	RequestBody        *string    `json:"request_body"`
	ResponseBody       *string    `json:"response_body"`
	ComplexityScore    *float64   `json:"complexity_score"`
	GuardrailLatencyMs *float64   `json:"guardrail_latency_ms"`
	LlmLatencyMs       *float64   `json:"llm_latency_ms"`
	QueuedLatencyMs    *float64   `json:"queued_latency_ms"`
	ClientIp           *string    `json:"client_ip"`
	TraceID            *string    `json:"trace_id"`
}

type ConfigAuditLog struct {
	ID          int64   `json:"id"`
	EntityType  string  `json:"entity_type"`
	EntityID    string  `json:"entity_id"`
	Action      string  `json:"action"`
	OldValues   *string `json:"old_values"`
	NewValues   *string `json:"new_values"`
	PerformedBy *string `json:"performed_by"`
	PerformedAt string  `json:"performed_at"`
}

type ConfigSetting struct {
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id"`
	Field   string `json:"field"`
	Value   string `json:"value"`
}

type Conversation struct {
	ID        string    `json:"id"`
	Title     string    `json:"title"`
	KeyID     *string   `json:"key_id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Group struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Metadata    *string   `json:"metadata"`
	Budget      *float64  `json:"budget"`
	DailyLimit  *float64  `json:"daily_limit"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type GuardrailEvent struct {
	ID            int64      `json:"id"`
	Timestamp     *time.Time `json:"timestamp"`
	KeyID         *string    `json:"key_id"`
	GuardrailType string     `json:"guardrail_type"`
	ActionTaken   string     `json:"action_taken"`
	Model         *string    `json:"model"`
	Provider      *string    `json:"provider"`
	Details       *string    `json:"details"`
	RequestID     *int64     `json:"request_id"`
}

type GuardrailRule struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Patterns    string    `json:"patterns"`
	Mode        string    `json:"mode"`
	Severity    string    `json:"severity"`
	Enabled     int64     `json:"enabled"`
	Type        string    `json:"type"`
	TargetType  *string   `json:"target_type"`
	TargetID    *int64    `json:"target_id"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Job struct {
	ID              string    `json:"id"`
	Name            string    `json:"name"`
	Description     *string   `json:"description"`
	Steps           string    `json:"steps"`
	VariablesConfig *string   `json:"variables_config"`
	DeliveryConfig  *string   `json:"delivery_config"`
	TimeoutMs       *int64    `json:"timeout_ms"`
	Enabled         int64     `json:"enabled"`
	ApiKeyID        *string   `json:"api_key_id"`
	CreatedAt       time.Time `json:"created_at"`
	UpdatedAt       time.Time `json:"updated_at"`
}

type JobActivation struct {
	ID        int64     `json:"id"`
	TriggerID string    `json:"trigger_id"`
	JobID     string    `json:"job_id"`
	IdemKey   string    `json:"idem_key"`
	Payload   []byte    `json:"payload"`
	Status    string    `json:"status"`
	RunID     *string   `json:"run_id"`
	CreatedAt time.Time `json:"created_at"`
}

type JobRun struct {
	ID               string     `json:"id"`
	JobID            string     `json:"job_id"`
	Status           string     `json:"status"`
	TriggerID        *string    `json:"trigger_id"`
	IdempotencyKey   *string    `json:"idempotency_key"`
	ExecutionKey     *string    `json:"execution_key"`
	LlmResult        *string    `json:"llm_result"`
	LlmError         *string    `json:"llm_error"`
	DeliveryResult   *string    `json:"delivery_result"`
	DeliveryError    *string    `json:"delivery_error"`
	PromptTokens     *int64     `json:"prompt_tokens"`
	CompletionTokens *int64     `json:"completion_tokens"`
	CostUsd          *float64   `json:"cost_usd"`
	RequestBody      *string    `json:"request_body"`
	Steps            *string    `json:"steps"`
	Attempts         int64      `json:"attempts"`
	NextRetryAt      *time.Time `json:"next_retry_at"`
	LastError        *string    `json:"last_error"`
	StartedAt        *time.Time `json:"started_at"`
	CompletedAt      *time.Time `json:"completed_at"`
	DurationMs       *int64     `json:"duration_ms"`
}

type KeyUsage struct {
	ID           int64    `json:"id"`
	KeyID        string   `json:"key_id"`
	Date         string   `json:"date"`
	TokensIn     *int64   `json:"tokens_in"`
	TokensOut    *int64   `json:"tokens_out"`
	CostUsd      *float64 `json:"cost_usd"`
	RequestCount *int64   `json:"request_count"`
	Model        *string  `json:"model"`
	Provider     *string  `json:"provider"`
}

type LoopEvent struct {
	ID            int64      `json:"id"`
	DetectedAt    *time.Time `json:"detected_at"`
	KeyID         *string    `json:"key_id"`
	ClientIp      *string    `json:"client_ip"`
	PromptHash    *string    `json:"prompt_hash"`
	RepeatCount   *int64     `json:"repeat_count"`
	WindowSeconds *int64     `json:"window_seconds"`
	ActionTaken   *string    `json:"action_taken"`
	ResolvedAt    *time.Time `json:"resolved_at"`
}

type McpAuditLog struct {
	ID         int64     `json:"id"`
	KeyID      *string   `json:"key_id"`
	Tool       string    `json:"tool"`
	ServerID   *string   `json:"server_id"`
	Method     string    `json:"method"`
	Params     *string   `json:"params"`
	DurationMs *float64  `json:"duration_ms"`
	StatusCode *int64    `json:"status_code"`
	Success    int64     `json:"success"`
	ErrorMsg   *string   `json:"error_msg"`
	ClientIp   *string   `json:"client_ip"`
	CreatedAt  time.Time `json:"created_at"`
}

type McpGrant struct {
	ID          string    `json:"id"`
	SubjectType string    `json:"subject_type"`
	SubjectID   string    `json:"subject_id"`
	ServerID    string    `json:"server_id"`
	Tools       string    `json:"tools"`
	Effect      string    `json:"effect"`
	Enabled     int64     `json:"enabled"`
	Priority    int64     `json:"priority"`
	CreatedAt   time.Time `json:"created_at"`
}

type McpServer struct {
	ID          string          `json:"id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Transport   string          `json:"transport"`
	Url         *string         `json:"url"`
	Command     *string         `json:"command"`
	Args        *string         `json:"args"`
	Env         *string         `json:"env"`
	Handler     *string         `json:"handler"`
	Enabled     int64           `json:"enabled"`
	Timeout     *string         `json:"timeout"`
	TimeoutMs   *int64          `json:"timeout_ms"`
	MaxRetries  int64           `json:"max_retries"`
	AuthType    *string         `json:"auth_type"`
	AuthKeyEnv  *string         `json:"auth_key_env"`
	Config      json.RawMessage `json:"config"`
	CreatedAt   time.Time       `json:"created_at"`
	UpdatedAt   time.Time       `json:"updated_at"`
}

type McpTool struct {
	ID          string          `json:"id"`
	ServerID    string          `json:"server_id"`
	Name        string          `json:"name"`
	Description *string         `json:"description"`
	Schema      json.RawMessage `json:"schema"`
	CreatedAt   time.Time       `json:"created_at"`
}

type Message struct {
	ID               int64     `json:"id"`
	ConversationID   string    `json:"conversation_id"`
	Role             string    `json:"role"`
	Content          string    `json:"content"`
	Model            *string   `json:"model"`
	TokenCount       *int64    `json:"token_count"`
	Cost             *float64  `json:"cost"`
	ReasoningContent *string   `json:"reasoning_content"`
	ToolCalls        *string   `json:"tool_calls"`
	UsageCost        *float64  `json:"usage_cost"`
	BillingKey       *string   `json:"billing_key"`
	CreatedAt        time.Time `json:"created_at"`
}

type ModelConfig struct {
	Name   string `json:"name"`
	Active int64  `json:"active"`
}

type OpenapiSpec struct {
	ID          string    `json:"id"`
	Name        string    `json:"name"`
	Description string    `json:"description"`
	SpecUrl     string    `json:"spec_url"`
	Operations  string    `json:"operations"`
	AuthType    string    `json:"auth_type"`
	AuthValue   string    `json:"auth_value"`
	AuthKey     string    `json:"auth_key"`
	TimeoutMs   int64     `json:"timeout_ms"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type Org struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type PiiEvent struct {
	ID                  int64      `json:"id"`
	Timestamp           *time.Time `json:"timestamp"`
	KeyID               *string    `json:"key_id"`
	RequestID           *int64     `json:"request_id"`
	PiiType             *string    `json:"pii_type"`
	ActionTaken         *string    `json:"action_taken"`
	MaskedPromptPreview *string    `json:"masked_prompt_preview"`
	ClientIp            *string    `json:"client_ip"`
	PiiValue            *string    `json:"pii_value"`
}

type PiiPattern struct {
	Name      string    `json:"name"`
	Regex     string    `json:"regex"`
	Enabled   int64     `json:"enabled"`
	Action    string    `json:"action"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type Prompt struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Description *string   `json:"description"`
	Version     string    `json:"version"`
	Content     string    `json:"content"`
	IsActive    int64     `json:"is_active"`
	Labels      *string   `json:"labels"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type PromptVersion struct {
	ID            int64     `json:"id"`
	PromptID      int64     `json:"prompt_id"`
	Version       string    `json:"version"`
	Content       string    `json:"content"`
	ChangeSummary *string   `json:"change_summary"`
	CreatedAt     time.Time `json:"created_at"`
}

type ProviderConfig struct {
	Name    string  `json:"name"`
	BaseUrl *string `json:"base_url"`
	ApiKey  *string `json:"api_key"`
}

type ProviderModel struct {
	ID               int64      `json:"id"`
	Provider         string     `json:"provider"`
	Model            string     `json:"model"`
	Active           int64      `json:"active"`
	Tier             string     `json:"tier"`
	CostIn           float64    `json:"cost_in"`
	CostOut          float64    `json:"cost_out"`
	DisplayName      *string    `json:"display_name"`
	MaxContextTokens *int64     `json:"max_context_tokens"`
	MaxOutputTokens  *int64     `json:"max_output_tokens"`
	Capabilities     *string    `json:"capabilities"`
	DefaultBaseUrl   *string    `json:"default_base_url"`
	DiscoveredAt     *time.Time `json:"discovered_at"`
}

type RoutingRule struct {
	ID          int64     `json:"id"`
	Name        string    `json:"name"`
	Condition   string    `json:"condition"`
	TargetModel string    `json:"target_model"`
	Priority    int64     `json:"priority"`
	Enabled     int64     `json:"enabled"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

type RuntimeConfig struct {
	Section   string    `json:"section"`
	Key       string    `json:"key"`
	Value     string    `json:"value"`
	Version   int64     `json:"version"`
	UpdatedAt time.Time `json:"updated_at"`
	UpdatedBy *string   `json:"updated_by"`
}

type RuntimeSchemaVersion struct {
	Version   int64  `json:"version"`
	AppliedAt string `json:"applied_at"`
	Checksum  string `json:"checksum"`
}

type Team struct {
	ID        string    `json:"id"`
	Name      string    `json:"name"`
	CreatedAt time.Time `json:"created_at"`
}

type Trigger struct {
	ID         string     `json:"id"`
	JobID      string     `json:"job_id"`
	Kind       string     `json:"kind"`
	Enabled    int64      `json:"enabled"`
	Config     string     `json:"config"`
	Token      *string    `json:"token"`
	SecretHash *string    `json:"secret_hash"`
	LastUsedAt *time.Time `json:"last_used_at"`
	CreatedAt  time.Time  `json:"created_at"`
	UpdatedAt  time.Time  `json:"updated_at"`
}

type UsageDaily struct {
	ID               int64    `json:"id"`
	KeyID            *string  `json:"key_id"`
	Date             *string  `json:"date"`
	Model            *string  `json:"model"`
	Provider         *string  `json:"provider"`
	Tokens           *int64   `json:"tokens"`
	Cost             *float64 `json:"cost"`
	RequestCount     *int64   `json:"request_count"`
	PromptTokens     *int64   `json:"prompt_tokens"`
	CompletionTokens *int64   `json:"completion_tokens"`
	CacheHits        *int64   `json:"cache_hits"`
}

type User struct {
	ID           int64     `json:"id"`
	Name         string    `json:"name"`
	Email        string    `json:"email"`
	Status       string    `json:"status"`
	PasswordHash *string   `json:"password_hash"`
	Metadata     *string   `json:"metadata"`
	Budget       *float64  `json:"budget"`
	DailyLimit   *float64  `json:"daily_limit"`
	CreatedAt    time.Time `json:"created_at"`
	UpdatedAt    time.Time `json:"updated_at"`
}

type UserGroupMembership struct {
	UserID    int64     `json:"user_id"`
	GroupID   int64     `json:"group_id"`
	Role      string    `json:"role"`
	CreatedAt time.Time `json:"created_at"`
}
