// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: prompts.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createPrompt = `-- name: CreatePrompt :execresult

INSERT INTO prompts (name, description, version, content, is_active, labels)
VALUES (?, ?, ?, ?, ?, ?)
`

type CreatePromptParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Version     string  `json:"version"`
	Content     string  `json:"content"`
	IsActive    int64   `json:"is_active"`
	Labels      *string `json:"labels"`
}

// Prompt templates queries.
func (q *Queries) CreatePrompt(ctx context.Context, arg CreatePromptParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createPrompt,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Content,
		arg.IsActive,
		arg.Labels,
	)
}

const createPromptVersion = `-- name: CreatePromptVersion :exec
INSERT INTO prompt_versions (prompt_id, version, content, change_summary)
VALUES (?, ?, ?, ?)
`

type CreatePromptVersionParams struct {
	PromptID      int64   `json:"prompt_id"`
	Version       string  `json:"version"`
	Content       string  `json:"content"`
	ChangeSummary *string `json:"change_summary"`
}

func (q *Queries) CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) error {
	_, err := q.db.ExecContext(ctx, createPromptVersion,
		arg.PromptID,
		arg.Version,
		arg.Content,
		arg.ChangeSummary,
	)
	return err
}

const deletePromptTemplate = `-- name: DeletePromptTemplate :execrows
DELETE FROM prompts WHERE id = ?
`

func (q *Queries) DeletePromptTemplate(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deletePromptTemplate, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getPromptTemplate = `-- name: GetPromptTemplate :one
SELECT id, name, description, version, content, is_active, labels, created_at, updated_at
FROM prompts WHERE id = ?
`

func (q *Queries) GetPromptTemplate(ctx context.Context, id int64) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplate, id)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Content,
		&i.IsActive,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateByName = `-- name: GetPromptTemplateByName :one
SELECT id, name, description, version, content, is_active, labels, created_at, updated_at
FROM prompts WHERE name = ?
`

func (q *Queries) GetPromptTemplateByName(ctx context.Context, name string) (Prompt, error) {
	row := q.db.QueryRowContext(ctx, getPromptTemplateByName, name)
	var i Prompt
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.Content,
		&i.IsActive,
		&i.Labels,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPromptTemplateVersions = `-- name: GetPromptTemplateVersions :many
SELECT id, prompt_id, version, content, change_summary, created_at
FROM prompt_versions WHERE prompt_id = ? ORDER BY id DESC
`

func (q *Queries) GetPromptTemplateVersions(ctx context.Context, promptID int64) ([]PromptVersion, error) {
	rows, err := q.db.QueryContext(ctx, getPromptTemplateVersions, promptID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PromptVersion{}
	for rows.Next() {
		var i PromptVersion
		if err := rows.Scan(
			&i.ID,
			&i.PromptID,
			&i.Version,
			&i.Content,
			&i.ChangeSummary,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPromptTemplates = `-- name: ListPromptTemplates :many
SELECT id, name, description, version, content, is_active, labels, created_at, updated_at
FROM prompts ORDER BY name
`

func (q *Queries) ListPromptTemplates(ctx context.Context) ([]Prompt, error) {
	rows, err := q.db.QueryContext(ctx, listPromptTemplates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Prompt{}
	for rows.Next() {
		var i Prompt
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.Content,
			&i.IsActive,
			&i.Labels,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePrompt = `-- name: UpdatePrompt :exec
UPDATE prompts SET name = ?, description = ?, version = ?, content = ?,
    is_active = ?, labels = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdatePromptParams struct {
	Name        string  `json:"name"`
	Description *string `json:"description"`
	Version     string  `json:"version"`
	Content     string  `json:"content"`
	IsActive    int64   `json:"is_active"`
	Labels      *string `json:"labels"`
	ID          int64   `json:"id"`
}

func (q *Queries) UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error {
	_, err := q.db.ExecContext(ctx, updatePrompt,
		arg.Name,
		arg.Description,
		arg.Version,
		arg.Content,
		arg.IsActive,
		arg.Labels,
		arg.ID,
	)
	return err
}
