// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provider_models.sql

package sqlc

import (
	"context"
)

const getActiveProviderModels = `-- name: GetActiveProviderModels :many
SELECT id, provider, model, active, tier, cost_in, cost_out,
    display_name, max_context_tokens, max_output_tokens,
    capabilities, default_base_url, discovered_at
FROM provider_models
WHERE active = 1
ORDER BY provider, model
`

func (q *Queries) GetActiveProviderModels(ctx context.Context) ([]ProviderModel, error) {
	rows, err := q.db.QueryContext(ctx, getActiveProviderModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderModel{}
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Active,
			&i.Tier,
			&i.CostIn,
			&i.CostOut,
			&i.DisplayName,
			&i.MaxContextTokens,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.DefaultBaseUrl,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllProviderModels = `-- name: GetAllProviderModels :many

SELECT id, provider, model, active, tier, cost_in, cost_out,
    display_name, max_context_tokens, max_output_tokens,
    capabilities, default_base_url, discovered_at
FROM provider_models
ORDER BY provider, model
`

// Provider models queries.
func (q *Queries) GetAllProviderModels(ctx context.Context) ([]ProviderModel, error) {
	rows, err := q.db.QueryContext(ctx, getAllProviderModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderModel{}
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Active,
			&i.Tier,
			&i.CostIn,
			&i.CostOut,
			&i.DisplayName,
			&i.MaxContextTokens,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.DefaultBaseUrl,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInactiveModels = `-- name: GetInactiveModels :many
SELECT model FROM provider_models WHERE active = 0
`

func (q *Queries) GetInactiveModels(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getInactiveModels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var model string
		if err := rows.Scan(&model); err != nil {
			return nil, err
		}
		items = append(items, model)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestDiscovery = `-- name: GetLatestDiscovery :one
SELECT COALESCE(MAX(discovered_at), '') FROM provider_models WHERE provider = ?
`

func (q *Queries) GetLatestDiscovery(ctx context.Context, provider string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestDiscovery, provider)
	var coalesce interface{}
	err := row.Scan(&coalesce)
	return coalesce, err
}

const getModelStatuses = `-- name: GetModelStatuses :many
SELECT model, active FROM provider_models
`

type GetModelStatusesRow struct {
	Model  string `json:"model"`
	Active int64  `json:"active"`
}

func (q *Queries) GetModelStatuses(ctx context.Context) ([]GetModelStatusesRow, error) {
	rows, err := q.db.QueryContext(ctx, getModelStatuses)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetModelStatusesRow{}
	for rows.Next() {
		var i GetModelStatusesRow
		if err := rows.Scan(&i.Model, &i.Active); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProviderForModel = `-- name: GetProviderForModel :one
SELECT provider FROM provider_models WHERE model = ? LIMIT 1
`

func (q *Queries) GetProviderForModel(ctx context.Context, model string) (string, error) {
	row := q.db.QueryRowContext(ctx, getProviderForModel, model)
	var provider string
	err := row.Scan(&provider)
	return provider, err
}

const getProviderModels = `-- name: GetProviderModels :many
SELECT id, provider, model, active, tier, cost_in, cost_out,
    display_name, max_context_tokens, max_output_tokens,
    capabilities, default_base_url, discovered_at
FROM provider_models
WHERE provider = ?
ORDER BY model
`

func (q *Queries) GetProviderModels(ctx context.Context, provider string) ([]ProviderModel, error) {
	rows, err := q.db.QueryContext(ctx, getProviderModels, provider)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProviderModel{}
	for rows.Next() {
		var i ProviderModel
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.Model,
			&i.Active,
			&i.Tier,
			&i.CostIn,
			&i.CostOut,
			&i.DisplayName,
			&i.MaxContextTokens,
			&i.MaxOutputTokens,
			&i.Capabilities,
			&i.DefaultBaseUrl,
			&i.DiscoveredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const providerModelCount = `-- name: ProviderModelCount :one
SELECT COUNT(*) FROM provider_models WHERE provider = ?
`

func (q *Queries) ProviderModelCount(ctx context.Context, provider string) (int64, error) {
	row := q.db.QueryRowContext(ctx, providerModelCount, provider)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const saveModelStatus = `-- name: SaveModelStatus :exec
UPDATE provider_models SET active = ? WHERE model = ?
`

type SaveModelStatusParams struct {
	Active int64  `json:"active"`
	Model  string `json:"model"`
}

func (q *Queries) SaveModelStatus(ctx context.Context, arg SaveModelStatusParams) error {
	_, err := q.db.ExecContext(ctx, saveModelStatus, arg.Active, arg.Model)
	return err
}

const saveModelTier = `-- name: SaveModelTier :exec
UPDATE provider_models SET tier = ? WHERE model = ?
`

type SaveModelTierParams struct {
	Tier  string `json:"tier"`
	Model string `json:"model"`
}

func (q *Queries) SaveModelTier(ctx context.Context, arg SaveModelTierParams) error {
	_, err := q.db.ExecContext(ctx, saveModelTier, arg.Tier, arg.Model)
	return err
}
