// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	AddUserToGroup(ctx context.Context, arg AddUserToGroupParams) error
	ConversationExists(ctx context.Context, id string) (int64, error)
	CountAPIKeys(ctx context.Context) (CountAPIKeysRow, error)
	// API keys queries.
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error
	CreateConversation(ctx context.Context, arg CreateConversationParams) error
	// Groups and group membership queries.
	CreateGroup(ctx context.Context, arg CreateGroupParams) (sql.Result, error)
	CreateGuardrailRule(ctx context.Context, arg CreateGuardrailRuleParams) error
	// Prompt templates queries.
	CreatePrompt(ctx context.Context, arg CreatePromptParams) (sql.Result, error)
	CreatePromptVersion(ctx context.Context, arg CreatePromptVersionParams) error
	// Users queries.
	CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error)
	DeleteAPIKey(ctx context.Context, id string) error
	DeleteConfig(ctx context.Context, arg DeleteConfigParams) error
	DeleteConfigSection(ctx context.Context, section string) error
	DeleteConversation(ctx context.Context, id string) (int64, error)
	DeleteGroup(ctx context.Context, id int64) (int64, error)
	DeleteGuardrailRule(ctx context.Context, id string) (int64, error)
	DeleteMCPToolsByServer(ctx context.Context, serverID string) error
	DeletePromptTemplate(ctx context.Context, id int64) (int64, error)
	DeleteUser(ctx context.Context, id int64) (int64, error)
	GetAPIKey(ctx context.Context, id string) (GetAPIKeyRow, error)
	GetAPIKeyByHash(ctx context.Context, hashedKey string) (GetAPIKeyByHashRow, error)
	GetAPIKeyTeamOrg(ctx context.Context, id string) (GetAPIKeyTeamOrgRow, error)
	GetAPIKeyWithHash(ctx context.Context, keyPrefix *string) (GetAPIKeyWithHashRow, error)
	GetAPIKeyWithHashNoPrefix(ctx context.Context) (GetAPIKeyWithHashNoPrefixRow, error)
	GetActiveProviderModels(ctx context.Context) ([]ProviderModel, error)
	GetAllConfig(ctx context.Context) ([]GetAllConfigRow, error)
	// Provider models queries.
	GetAllProviderModels(ctx context.Context) ([]ProviderModel, error)
	// runtime_config queries
	// Runtime configuration key-value store for feature flags, routing, and provider configs.
	GetConfig(ctx context.Context, arg GetConfigParams) (GetConfigRow, error)
	GetConfigSection(ctx context.Context, section string) ([]GetConfigSectionRow, error)
	// Config settings queries.
	GetConfigSetting(ctx context.Context, arg GetConfigSettingParams) (string, error)
	GetConversation(ctx context.Context, id string) (GetConversationRow, error)
	GetCurrentMonthUsage(ctx context.Context, arg GetCurrentMonthUsageParams) (interface{}, error)
	GetEnabledGuardrailRules(ctx context.Context) ([]GetEnabledGuardrailRulesRow, error)
	GetGroup(ctx context.Context, id int64) (Group, error)
	GetGroupBudget(ctx context.Context, id int64) (GetGroupBudgetRow, error)
	GetGroupByName(ctx context.Context, name string) (Group, error)
	GetGroupUsers(ctx context.Context, groupID int64) ([]User, error)
	GetInactiveModels(ctx context.Context) ([]string, error)
	GetKeyUsage(ctx context.Context, arg GetKeyUsageParams) ([]GetKeyUsageRow, error)
	GetLatestDiscovery(ctx context.Context, provider string) (interface{}, error)
	GetMessageCreatedAt(ctx context.Context, id int64) (time.Time, error)
	GetModelStatuses(ctx context.Context) ([]GetModelStatusesRow, error)
	GetPromptTemplate(ctx context.Context, id int64) (Prompt, error)
	GetPromptTemplateByName(ctx context.Context, name string) (Prompt, error)
	GetPromptTemplateVersions(ctx context.Context, promptID int64) ([]PromptVersion, error)
	GetProviderForModel(ctx context.Context, model string) (string, error)
	GetProviderModels(ctx context.Context, provider string) ([]ProviderModel, error)
	GetUsageSummary(ctx context.Context) (GetUsageSummaryRow, error)
	GetUser(ctx context.Context, id int64) (User, error)
	GetUserBudget(ctx context.Context, id int64) (GetUserBudgetRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserGroups(ctx context.Context, userID int64) ([]Group, error)
	InsertGuardrailEvent(ctx context.Context, arg InsertGuardrailEventParams) error
	InsertMessage(ctx context.Context, arg InsertMessageParams) (int64, error)
	ListAPIKeys(ctx context.Context) ([]ListAPIKeysRow, error)
	ListAPIKeysByGroup(ctx context.Context, groupID *int64) ([]ListAPIKeysByGroupRow, error)
	// Chat conversations and messages (dashboard chat UI).
	ListConversations(ctx context.Context) ([]ListConversationsRow, error)
	ListGroups(ctx context.Context) ([]Group, error)
	// Guardrail rules (CRUD) and guardrail events (write path).
	ListGuardrailRules(ctx context.Context) ([]ListGuardrailRulesRow, error)
	// MCP server registry: servers config and their discovered tools.
	ListMCPServers(ctx context.Context) ([]ListMCPServersRow, error)
	ListMCPTools(ctx context.Context, serverID string) ([]ListMCPToolsRow, error)
	ListMessagesByConversation(ctx context.Context, conversationID string) ([]Message, error)
	ListMessagesPaginated(ctx context.Context, arg ListMessagesPaginatedParams) ([]Message, error)
	ListPromptTemplates(ctx context.Context) ([]Prompt, error)
	ListUsers(ctx context.Context) ([]User, error)
	LogConfigCreate(ctx context.Context, arg LogConfigCreateParams) error
	LogConfigDelete(ctx context.Context, arg LogConfigDeleteParams) error
	LogConfigUpdate(ctx context.Context, arg LogConfigUpdateParams) error
	ProviderModelCount(ctx context.Context, provider string) (int64, error)
	// Daily usage aggregation queries.
	RecordDailyUsage(ctx context.Context, arg RecordDailyUsageParams) error
	// Key usage aggregation queries.
	RecordKeyUsage(ctx context.Context, arg RecordKeyUsageParams) error
	RemoveUserFromGroup(ctx context.Context, arg RemoveUserFromGroupParams) (int64, error)
	SaveModelStatus(ctx context.Context, arg SaveModelStatusParams) error
	SaveModelTier(ctx context.Context, arg SaveModelTierParams) error
	SetConversationTitle(ctx context.Context, arg SetConversationTitleParams) error
	SetKeyRateLimit(ctx context.Context, arg SetKeyRateLimitParams) error
	ToggleGuardrailRule(ctx context.Context, arg ToggleGuardrailRuleParams) (int64, error)
	TouchConversation(ctx context.Context, id string) error
	UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error
	UpdateConversationTitle(ctx context.Context, arg UpdateConversationTitleParams) (int64, error)
	UpdateGuardrailRule(ctx context.Context, arg UpdateGuardrailRuleParams) (int64, error)
	UpdatePrompt(ctx context.Context, arg UpdatePromptParams) error
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) error
	UpsertMCPTool(ctx context.Context, arg UpsertMCPToolParams) error
}

var _ Querier = (*Queries)(nil)
