// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtime_config.sql

package sqlc

import (
	"context"
)

const deleteConfig = `-- name: DeleteConfig :exec
DELETE FROM runtime_config
WHERE section = ? AND key = ?
`

type DeleteConfigParams struct {
	Section string `json:"section"`
	Key     string `json:"key"`
}

func (q *Queries) DeleteConfig(ctx context.Context, arg DeleteConfigParams) error {
	_, err := q.db.ExecContext(ctx, deleteConfig, arg.Section, arg.Key)
	return err
}

const deleteConfigSection = `-- name: DeleteConfigSection :exec
DELETE FROM runtime_config
WHERE section = ?
`

func (q *Queries) DeleteConfigSection(ctx context.Context, section string) error {
	_, err := q.db.ExecContext(ctx, deleteConfigSection, section)
	return err
}

const getAllConfig = `-- name: GetAllConfig :many
SELECT section, key, value
FROM runtime_config
ORDER BY section, key
`

type GetAllConfigRow struct {
	Section string `json:"section"`
	Key     string `json:"key"`
	Value   string `json:"value"`
}

func (q *Queries) GetAllConfig(ctx context.Context) ([]GetAllConfigRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllConfigRow{}
	for rows.Next() {
		var i GetAllConfigRow
		if err := rows.Scan(&i.Section, &i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfig = `-- name: GetConfig :one

SELECT section, key, value, version, COALESCE(updated_by, '') AS updated_by
FROM runtime_config
WHERE section = ? AND key = ?
`

type GetConfigParams struct {
	Section string `json:"section"`
	Key     string `json:"key"`
}

type GetConfigRow struct {
	Section   string `json:"section"`
	Key       string `json:"key"`
	Value     string `json:"value"`
	Version   int64  `json:"version"`
	UpdatedBy string `json:"updated_by"`
}

// runtime_config queries
// Runtime configuration key-value store for feature flags, routing, and provider configs.
func (q *Queries) GetConfig(ctx context.Context, arg GetConfigParams) (GetConfigRow, error) {
	row := q.db.QueryRowContext(ctx, getConfig, arg.Section, arg.Key)
	var i GetConfigRow
	err := row.Scan(
		&i.Section,
		&i.Key,
		&i.Value,
		&i.Version,
		&i.UpdatedBy,
	)
	return i, err
}

const getConfigSection = `-- name: GetConfigSection :many
SELECT key, value
FROM runtime_config
WHERE section = ?
ORDER BY key
`

type GetConfigSectionRow struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) GetConfigSection(ctx context.Context, section string) ([]GetConfigSectionRow, error) {
	rows, err := q.db.QueryContext(ctx, getConfigSection, section)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetConfigSectionRow{}
	for rows.Next() {
		var i GetConfigSectionRow
		if err := rows.Scan(&i.Key, &i.Value); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertConfig = `-- name: UpsertConfig :exec
INSERT INTO runtime_config (section, key, value, version, updated_by)
VALUES (?, ?, ?, 1, ?)
ON CONFLICT(section, key) DO UPDATE SET
    value = excluded.value,
    version = version + 1,
    updated_at = datetime('now'),
    updated_by = excluded.updated_by
`

type UpsertConfigParams struct {
	Section   string  `json:"section"`
	Key       string  `json:"key"`
	Value     string  `json:"value"`
	UpdatedBy *string `json:"updated_by"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) error {
	_, err := q.db.ExecContext(ctx, upsertConfig,
		arg.Section,
		arg.Key,
		arg.Value,
		arg.UpdatedBy,
	)
	return err
}
