// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: usage_daily.sql

package sqlc

import (
	"context"
)

const recordDailyUsage = `-- name: RecordDailyUsage :exec

INSERT INTO usage_daily (key_id, date, model, provider, tokens, cost, request_count, prompt_tokens, completion_tokens, cache_hits)
VALUES (?, ?, ?, ?, ?, ?, 1, ?, ?, ?)
ON CONFLICT(key_id, date, model, provider) DO UPDATE SET
    tokens = tokens + excluded.tokens,
    cost = cost + excluded.cost,
    request_count = request_count + 1,
    prompt_tokens = prompt_tokens + excluded.prompt_tokens,
    completion_tokens = completion_tokens + excluded.completion_tokens,
    cache_hits = cache_hits + excluded.cache_hits
`

type RecordDailyUsageParams struct {
	KeyID            *string  `json:"key_id"`
	Date             *string  `json:"date"`
	Model            *string  `json:"model"`
	Provider         *string  `json:"provider"`
	Tokens           *int64   `json:"tokens"`
	Cost             *float64 `json:"cost"`
	PromptTokens     *int64   `json:"prompt_tokens"`
	CompletionTokens *int64   `json:"completion_tokens"`
	CacheHits        *int64   `json:"cache_hits"`
}

// Daily usage aggregation queries.
func (q *Queries) RecordDailyUsage(ctx context.Context, arg RecordDailyUsageParams) error {
	_, err := q.db.ExecContext(ctx, recordDailyUsage,
		arg.KeyID,
		arg.Date,
		arg.Model,
		arg.Provider,
		arg.Tokens,
		arg.Cost,
		arg.PromptTokens,
		arg.CompletionTokens,
		arg.CacheHits,
	)
	return err
}
