// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createUser = `-- name: CreateUser :execresult

INSERT INTO users (name, email, status, metadata, budget, password_hash)
VALUES (?, ?, ?, '{}', ?, ?)
`

type CreateUserParams struct {
	Name         string   `json:"name"`
	Email        string   `json:"email"`
	Status       string   `json:"status"`
	Budget       *float64 `json:"budget"`
	PasswordHash *string  `json:"password_hash"`
}

// Users queries.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Status,
		arg.Budget,
		arg.PasswordHash,
	)
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, status, password_hash, metadata, budget, daily_limit, created_at, updated_at
FROM users WHERE id = ?
`

func (q *Queries) GetUser(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.PasswordHash,
		&i.Metadata,
		&i.Budget,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserBudget = `-- name: GetUserBudget :one
SELECT budget, daily_limit FROM users WHERE id = ?
`

type GetUserBudgetRow struct {
	Budget     *float64 `json:"budget"`
	DailyLimit *float64 `json:"daily_limit"`
}

func (q *Queries) GetUserBudget(ctx context.Context, id int64) (GetUserBudgetRow, error) {
	row := q.db.QueryRowContext(ctx, getUserBudget, id)
	var i GetUserBudgetRow
	err := row.Scan(&i.Budget, &i.DailyLimit)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, status, password_hash, metadata, budget, daily_limit, created_at, updated_at
FROM users WHERE email = ?
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Status,
		&i.PasswordHash,
		&i.Metadata,
		&i.Budget,
		&i.DailyLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, status, password_hash, metadata, budget, daily_limit, created_at, updated_at
FROM users ORDER BY id
`

func (q *Queries) ListUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Status,
			&i.PasswordHash,
			&i.Metadata,
			&i.Budget,
			&i.DailyLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
