package web

import (
	"embed"
)

// DistFS contains the built Astro dashboard static files (HTML, JS, CSS, assets).
// Generated by `bun run build` in the web/ directory, embedded at Go compile time.
//
//go:embed all:dist
var DistFS embed.FS
